services:
  sni5gect:
    image: sni5gect
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sni5gect
    privileged: true
    restart: unless-stopped
    entrypoint: /sbin/init
    network_mode: host
    volumes:
      - "/dev/:/dev/"
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 1G
