services:
  sni5gect:
    image: ghcr.io/cueltschey/sni5gect
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sni5gect
    privileged: true
    network_mode: host
    volumes:
      - "/dev/:/dev/"
      - ./configs:/configs
      - /home/charles/collected_iq:/iq
    deploy:
      resources:
        reservations:
          cpus: '1'
          memory: 1G
