cell:
  band: 3 # Band number
  nof_prb: 106 # Number of Physical Resource Blocks
  scs_common: 15 # Subcarrier Spacing for common (kHz)
  scs_ssb: 15 # Subcarrier Spacing for SSB (kHz)
  ssb_period_ms: 1 # SSB periodicity in milliseconds
  dl_arfcn: 368500 # Downlink ARFCN
  ssb_arfcn: 368410 # SSB ARFCN

source:
  source_type: uhd
  source_params: type=b200,master_clock_rate=23.04e6

enable_recorder: false # record the IQ samples to file
pcap_folder: logs/

rf:
  sample_rate: 23.04e6
  num_channels: 1
  uplink_cfo: 0 # Uplink Carrier Frequency Offset correction in Hz
  downlink_cfo: 0 # Downlink Carrier Frequency Offset (CFO) in Hz
  padding:
    front_padding: 0 # Number of IQ samples to pad in front of each burst
    back_padding: 0 # Number of IQ samples to pad at the end of each burst
  channels:
    - rx_frequency: 1842.5e6
      tx_frequency: 1842.5e6
      rx_offset: 0
      tx_offset: 3000
      rx_gain: 40
      tx_gain: 50
      enable: true
    - rx_frequency: 1747.5e6
      tx_frequency: 1747.5e6
      rx_offset: 0
      tx_offset: 0
      rx_gain: 40
      tx_gain: 50
      enable: false

workers:
  pool_size: 24 # Worker pool size
  n_ue_dl_worker: 4 # Number of UE downlink workers
  n_ue_ul_worker: 4 # Number of UE uplink workers
  n_gnb_dl_worker: 4 # Number of gNB downlink workers
  n_gnb_ul_worker: 4 # Number of gNB uplink workers

uetracker:
  close_timeout: 5000 # ms: stop tracking if no messages received
  parse_messages: true # Parse messages
  num_ues: 1 # Number of UETrackers to pre-initialize
  enable_gpu: false # GPU acceleration for decoding

downlink_injector:
  delay_n_slots: 5 # Number of slots to delay injecting the message
  duplications: 2 # Number of duplications to send in each inject
  tx_cfo_correction: 0 # Uplink CFO correction (Hz)
  tx_advancement: 160 # Number of samples to send in advance
  pdsch_mcs: 3 # PDSCH MCS
  pdsch_prbs: 24 # PDSCH PRBs

databases:
  - enable: true
    host: "0.0.0.0"
    port: 8086
    org: "rtu"
    token: "605bc59413b7d5457d181ccf20f9fda15693f81b068d70396cc183081b264f3b"
    bucket: "rtusystem"
    data_id: "test"

log:
  log_level: INFO
  syncer: INFO
  worker: INFO
  bc_worker: INFO

exploit: build/modules/lib_dummy_exploit.so # exploit module to use
